//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.IC.RecursosTexto {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesBase() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.IC.RecursosTexto.MensajesBase", typeof(MensajesBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta exitosa..
        /// </summary>
        public static string ConsultaExitosa {
            get {
                return ResourceManager.GetString("ConsultaExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta fallida..
        /// </summary>
        public static string ConsultaFallida {
            get {
                return ResourceManager.GetString("ConsultaFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dato no actualizado..
        /// </summary>
        public static string DatoNoActualizado {
            get {
                return ResourceManager.GetString("DatoNoActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dato no encontrado..
        /// </summary>
        public static string DatoNoEncontrado {
            get {
                return ResourceManager.GetString("DatoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos editados..
        /// </summary>
        public static string DatosEditados {
            get {
                return ResourceManager.GetString("DatosEditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos no editados..
        /// </summary>
        public static string DatosNoEditados {
            get {
                return ResourceManager.GetString("DatosNoEditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminacion exitosa..
        /// </summary>
        public static string EliminacionExitosa {
            get {
                return ResourceManager.GetString("EliminacionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminacion fallida..
        /// </summary>
        public static string EliminacionFallida {
            get {
                return ResourceManager.GetString("EliminacionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado exitoso..
        /// </summary>
        public static string GuardadoExitoso {
            get {
                return ResourceManager.GetString("GuardadoExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado fallido..
        /// </summary>
        public static string GuardadoFallido {
            get {
                return ResourceManager.GetString("GuardadoFallido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion fallida..
        /// </summary>
        public static string OperacionFallida {
            get {
                return ResourceManager.GetString("OperacionFallida", resourceCulture);
            }
        }
    }
}
