// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;


namespace Base.Datos.Migrations
{
    [DbContext(typeof(Base.Datos.Contexto.Contexto))]
    [Migration("20200822140845_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.Cliente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Codigo")
                        .HasName("PK__Cliente__06370DADD835A887");

                    b.HasIndex("Cedula")
                        .IsUnique()
                        .HasName("UQ__Cliente__B4ADFE38FB4A6E10");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.Compra", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Codigo")
                        .HasName("PK__Compra__06370DAD216AE2A1");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.InventarioProducto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProducto")
                        .HasColumnType("int");

                    b.HasKey("Codigo")
                        .HasName("PK__Inventar__06370DAD1994EC35");

                    b.HasIndex("CodigoProducto");

                    b.ToTable("InventarioProducto");
                });

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.Producto", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Codigo")
                        .HasName("PK__Producto__06370DAD224BF5AA");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.ProductoCompraCliente", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.Property<int>("CodigoCompra")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProducto")
                        .HasColumnType("int");

                    b.HasKey("Codigo")
                        .HasName("PK__Producto__06370DADAEFC38D6");

                    b.HasIndex("CodigoCliente");

                    b.HasIndex("CodigoCompra");

                    b.HasIndex("CodigoProducto");

                    b.ToTable("Producto_Compra_Cliente");
                });

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.InventarioProducto", b =>
                {
                    b.HasOne("Base.Datos.Contexto.Entidades.Producto", "CodigoProductoNavigation")
                        .WithMany("InventarioProducto")
                        .HasForeignKey("CodigoProducto")
                        .HasConstraintName("FK_Productos_InventarioProductos_CodigoProducto")
                        .IsRequired();
                });

            modelBuilder.Entity("Base.Datos.Contexto.Entidades.ProductoCompraCliente", b =>
                {
                    b.HasOne("Base.Datos.Contexto.Entidades.Cliente", "CodigoClienteNavigation")
                        .WithMany("ProductoCompraCliente")
                        .HasForeignKey("CodigoCliente")
                        .HasConstraintName("FK_Productos_Compras_Clientes_CodigoCliente")
                        .IsRequired();

                    b.HasOne("Base.Datos.Contexto.Entidades.Compra", "CodigoCompraNavigation")
                        .WithMany("ProductoCompraCliente")
                        .HasForeignKey("CodigoCompra")
                        .HasConstraintName("FK_Productos_Compras_Clientes_CodigoCompra")
                        .IsRequired();

                    b.HasOne("Base.Datos.Contexto.Entidades.Producto", "CodigoProductoNavigation")
                        .WithMany("ProductoCompraCliente")
                        .HasForeignKey("CodigoProducto")
                        .HasConstraintName("FK_Productos_Compras_Clientes_CodigoProducto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
